### ISSUE TITLE
Too many entities

### ISSUE THREAD

**Issue by frafra** [frafra/is-osm-uptodate#1]
If more than 50.000 entities are requested the API fails with an  HTTP status code 400 (Bad Request).
A insightful message should be displayed instead of the generic one.

**Comment by mmd-osm** [comment]
Besides, the osm api is meant for editing purposes only, and not for analytical use cases. You should probably look at Overpass API instead.

**Comment by frafra** [comment]
@mmd-osm thank you for your comment. I would love to switch to Overpass API, but they are not suitable for this task:

> Overpass API also can't give you full history of an object, but time-based selection criteria can give you the state of an object at a certain time.

-- https://wiki.openstreetmap.org/wiki/Overpass_API#Limitations

`is-osm-uptodate` comply with the technical usage requirements of the OSM API policy and it does not fall under the "Large or frequent data users" (requests are small and the program has a cache when run as webservice).

The current solution is not optimal, but it is the only way to get complete historical data from OSM on a global scale without having to download the whole planet file.

**Comment by mmd-osm** [comment]
I had this query in mind `REQUEST_TEMPLATE = PROTOCOL+SERVER+"/api/0.6/map?bbox={minx},{miny},{maxx},{maxy}"`, not the history call. That's why I added it to this issue, which apparently deals with the 50'000 nodes limits on the osm api.

**Comment by frafra** [comment]
Nice, they added it, thank you for the link. I opened a ticket for it: #2

**Comment by mmd-osm** [comment]
Thanks! I updated the wiki page in the meantime.
