### ISSUE TITLE
Empy page after search with the filter

### ISSUE THREAD

**Issue by LorenzoStucchi** [frafra/is-osm-uptodate#165]
Hi @frafra,

I tried to use your great tools but when I add a tag filter the results is just a white and empty page.

In the console I have this error:
`TypeError: t.geojson.features[s.indexOf(...)] is undefined`

**Comment by frafra** [comment]
I am sorry, I have rewritten the frontend from scratch, and it could be that you found a regression.
I will fix it this evening :)

**Comment by frafra** [comment]
It looks like that happens when there are no results.

Could you please check if the issue is solved here? https://is-osm-uptodate.fly.dev/

**Comment by LorenzoStucchi** [comment]
@frafra now it is working! I was searching for kerbs in an area without kerbs. But now it is working 😃
