### ISSUE TITLE
Exporting results from the web interface

### ISSUE THREAD

**Issue by MarcoMinghini** [frafra/is-osm-uptodate#3]
A useful improvement would be to enable exports of the following results from the web interface, after the user has fetched some data and seleted one of the quality parameters:

- the dataset of OSM nodes and ways with corresponding quality parameters (the same shown in the popup), e.g. in GeoJSON format
- the style of the dataset of OSM nodes and ways, for instance in the QGIS QML style format (suggested) or in SLD format

**Comment by frafra** [comment]
Implemented in commit 7c6e0705b59a0299b89c12ec2d4f55d6423a8692.

**Comment by MarcoMinghini** [comment]
Very curious to test this functionality! feel free to close the issue.
