### ISSUE TITLE
Perform the analysis on a custom (non rectangular) polygon

### ISSUE THREAD

**Issue by MarcoMinghini** [frafra/is-osm-uptodate#4]
A useful improvement could be to allow users to perform the analysis not only on a selected rectangular bounding box, but also on a custom area defined through the upload of a polygon (e.g. as a GeoJSON file). A constraint can be forced on the total surface of the polygon to be uploaded, to avoid making the analysis on areas which are too wide.

**Comment by frafra** [comment]
One of the main issue is that is a slow mechanism.
